### PR TITLE
hide min points to queue, display map select mode

### PR DESCRIPTION
**Pull request by torriz**
> Hiding Minimum Points to Queue if null? is there a better way of doing this? 
> Show MapSelection.Mode, with MapSelection.Mode ToString? 
> **__Map Info__**

### CODE REVIEW

**Comment by torriz** [comment]
Actually.. could perhaps use Fields (embed AddField) in the Lobbyinfo.cs => Lobby part instead ¯\_(ツ)_/¯
Could just do that later on tho.

**Comment by torriz** [comment]
+ What is your thoughts on using f.ex switch statements with the various toggle commands? 
Commands like: UpdateNicknames, ToggleDms (Old DMAnnouncements)
> To allow for also setting them with __f.ex__: `UpdateNicknames true` or `UpdateNicknames Yes`, but keeping the original "toggle" if no input?

If you have other BETTER ideas to allow for the inputs while also keeping the toggle, then do that instead

**Comment by PassiveModding** [comment]
For the MapSelection.Mode tostring stuff refer to this: https://stackoverflow.com/a/479417 for 'friendly' named enums. So you'd call that extension on the enum value to get the name instead of just the enum name.

And yeah I might do some polishing for some of the toggle commands so it would accept a nullable boolean as a parameter, if it's null then toggle, otherwise set.

**Comment by PassiveModding** [comment]
implemented in:
https://github.com/PassiveModding/RavenBOT/commit/36c2efc958778956277fddf06eaffaac2c5fab40

**Pull request closed without merging**
